#!/usr/bin/perl

use lib qw( /home/aupro/ap/perl/lib /home/aupro/usr/lib/perl );

use warnings;
use strict;

use Data::Dumper;
use Mamf::Common qw(json_retrieve);

if(not $ARGV[0]) {
  print "please request either:\nfailed\nor\nsuccess [sid]\n";
  exit;
}



my $g_home_dir=$ENV{'HOME'};
my $g_vert_stat_file="$g_home_dir/ap/var/vert_stat.json";

my $vert_stat_obj=json_retrieve($g_vert_stat_file);

if($ARGV[0] eq 'failed') {

  foreach my $failed_author (keys %{$vert_stat_obj->{'FAILED_CALCULATIONS'}}) {
    print "calculations for $failed_author failed at the following distances:\n";
    print keys %{$vert_stat_obj->{'FAILED_CALCULATIONS'}->{$failed_author}}, "\n";
  }
} elsif($ARGV[0] eq 'success') {
  my $sid=$ARGV[1];
  if(not $sid) {
    print "please request either:\nfailed\nor\nsuccess [sid]\n";
    exit;
  }
  print Dumper keys %{$vert_stat_obj->{$sid}};
}
