#!/usr/bin/perl

use strict;
use warnings;

use AuthorProfile::Network qw(find_edges);
use XML::LibXML;

my $file=$ARGV[0];
if(not defined($file)) {
  print "fatal: no file argument\n";
  exit;
}
if(not -f $file) {
  print "fatal: no such file '$file'\n";
  exit;
}

my $dom=XML::LibXML->new();


&find_edges($file,$dom);
