#!/usr/bin/perl

use strict;
use warnings;

use lib qw( /home/aupro/usr/lib/perl /home/aupro/ap/perl/lib );

use Data::Dumper;
use JSON::XS;

my $test_str='this is test string';
my $test_h;
$test_h->{'this'}='is';
$test_h->{'test'}='hash';
#print Dumper $test_h;
my $coder = JSON::XS->new->ascii->pretty->allow_nonref;
#print $coder->encode ($test_str);
my $json_h = $coder->encode($test_h);
my $json_text = JSON::XS->new->utf8->allow_nonref->encode($test_str);
print Dumper $json_h;
print $json_text,"\n";
print $coder->decode($json_text);

#print 'serialized: ', Dumper (encode_json $test_str);
